name: FlyPlugin
version: 1.0
main: com.yourname.flyplugin.Main
api-version: 1.21
dependencies: [Vault]
commands:
  flystart:
    description: 开启飞行并开始计费
  flystop:
    description: 关闭飞行并停止计费
  flyreload:
    description: 重载插件配置